---
- hosts: ios_devices
  gather_facts: yes
  connection: local

  tasks:
    - name: Install git - skipped if already installed
      yum: name=git state=installed

    - name: Create topology_mapper/ directory                                                  
      file: path=/root/topology_mapper/ state=directory owner=root group=root mode=0755

    - name: Clone topology_mapper repository
      git:
        repo: https://github.com/rtalukder/topology_mapper.git
        dest: /root/topology_mapper/
        clone: no
        update: yes


    - name: Create directories needed for topology_mapper script                                               
      file: path="/root/topology_mapper/{{ inventory_hostname }}" state=directory owner=root group=root mode=0755

    - name: Create directories needed for topology_mapper script                                               
      file: path="/root/topology_mapper/{{ inventory_hostname }}/{{ item }}" state=directory owner=root group=root mode=0755
      with_items:
        - ios_output
        - formatted_data
        - rarp_output

    - name: Run 'show mac address-table'
      ios_command:
        commands:
          - show mac address-table
      register: mac_output
    - debug: var=mac_output.stdout_lines

    - name: Save 'show mac address-table' output to a file
      local_action: copy content="{{ mac_output.stdout }}" dest="/root/topology_mapper/{{ inventory_hostname }}/ios_output/mac_output.{{ inventory_hostname }}.txt"
      register: mac_file
    - debug: var=mac_file.dest

    - name: Run 'show ip arp'
      ios_command:
        commands:
          - show ip arp
      register: arp_output
    - debug: var=arp_output.stdout_lines

    - name: Save 'show ip arp' output to a file
      local_action: copy content="{{ arp_output.stdout }}" dest="/root/topology_mapper/{{ inventory_hostname }}/ios_output/arp_output.{{ inventory_hostname }}.txt"
      register: arp_file
    - debug: var=arp_file.dest

    - name: Run topology_mapper script
      local_action: raw python3 /root/topology_mapper/file_parser.py "{{ arp_file.dest }}" "{{ mac_file.dest }}"
